Candidate: CVE-2013-4347
PublicDate: 2014-05-20 14:55:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4347
 http://www.openwall.com/lists/oss-security/2013/09/12/5
 https://github.com/simplegeo/python-oauth2/issues/9
Description:
 It was found that python-oauth2 did not properly generate random values for
 use in nonces. An attacker able to capture network traffic of a website
 using OAuth2 authentication could use this flaw to conduct replay attacks
 against that website.
Ubuntu-Description:
Notes:
Bugs:
 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=722657
 https://bugs.launchpad.net/ubuntu/+source/python-oauth2/+bug/1384815
Priority: medium
Discovered-by:
Assigned-to:
CVSS: 

Patches_python-oauth2:
upstream_python-oauth2: needs-triage
lucid_python-oauth2: DNE
precise_python-oauth2: ignored (reached end-of-life)
precise/esm_python-oauth2: DNE (precise was needed)
quantal_python-oauth2: ignored (reached end-of-life)
raring_python-oauth2: ignored (reached end-of-life)
saucy_python-oauth2: ignored (reached end-of-life)
trusty_python-oauth2: ignored (reached end-of-life)
trusty/esm_python-oauth2: DNE (trusty was needed)
utopic_python-oauth2: ignored (reached end-of-life)
vivid_python-oauth2: ignored (reached end-of-life)
vivid/stable-phone-overlay_python-oauth2: DNE
vivid/ubuntu-core_python-oauth2: DNE
wily_python-oauth2: DNE
xenial_python-oauth2: DNE
yakkety_python-oauth2: DNE
zesty_python-oauth2: DNE
artful_python-oauth2: DNE
bionic_python-oauth2: DNE
cosmic_python-oauth2: DNE
disco_python-oauth2: DNE
devel_python-oauth2: DNE
