Candidate: CVE-2021-46823
PublicDate: 2022-06-18 16:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-46823
 https://github.com/python-ldap/python-ldap/security/advisories/GHSA-r8wq-qrxc-hmcm
 https://exchange.xforce.ibmcloud.com/vulnerabilities/221507
Description:
 python-ldap before 3.4.0 is vulnerable to a denial of service when
 ldap.schema is used for untrusted schema definitions, because of a regular
 expression denial of service (ReDoS) flaw in the LDAP schema parser. By
 sending crafted regex input, a remote authenticated attacker could exploit
 this vulnerability to cause a denial of service condition.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H [6.5 MEDIUM]


Patches_python-ldap:
upstream_python-ldap: released (3.4.0-1)
bionic_python-ldap: needs-triage
focal_python-ldap: needs-triage
impish_python-ldap: needs-triage
jammy_python-ldap: needs-triage
devel_python-ldap: needs-triage
