Candidate: CVE-2023-29824
PublicDate: 2023-07-06
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-29824
 http://www.square16.org/achievement/cve-2023-29824/
 https://github.com/scipy/scipy/pull/15013
Description:
 A use-after-free issue was discovered in Py_FindObjects() function in SciPy
 versions prior to 1.8.0.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
 https://github.com/scipy/scipy/issues/14713
Priority: medium
Discovered-by:
Assigned-to:
CVSS:

Patches_scipy:
upstream_scipy: needs-triage
trusty_scipy: ignored (end of standard support)
xenial_scipy: ignored (end of standard support)
bionic_scipy: ignored (end of standard support)
focal_scipy: needs-triage
esm-apps/focal_scipy: needs-triage
jammy_scipy: needs-triage
esm-apps/jammy_scipy: needs-triage
kinetic_scipy: needs-triage
lunar_scipy: needs-triage
devel_scipy: needs-triage
