Candidate: CVE-2023-28858
PublicDate: 2023-03-26 19:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28858
 https://github.com/redis/redis-py/compare/v4.3.5...v4.3.6
 https://github.com/redis/redis-py/pull/2641
 https://openai.com/blog/march-20-chatgpt-outage
 https://github.com/redis/redis-py/issues/2624
 https://github.com/redis/redis-py/compare/v4.4.2...v4.4.3
 https://github.com/redis/redis-py/compare/v4.5.2...v4.5.3
Description:
 redis-py before 4.5.3 leaves a connection open after canceling an async
 Redis command at an inopportune time, and can send response data to the
 client of an unrelated request in an off-by-one manner. NOTE: this CVE
 Record was initially created in response to reports about ChatGPT, and
 4.3.6, 4.4.3, and 4.5.3 were released (changing the behavior for pipeline
 operations); however, please see CVE-2023-28859 about addressing data
 leakage across AsyncIO connections in general.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N [3.7 LOW]

Patches_python-redis:
upstream_python-redis: needs-triage
esm-infra/xenial_python-redis: needs-triage
trusty_python-redis: ignored (out of standard support)
xenial_python-redis: ignored (out of standard support)
bionic_python-redis: needs-triage
focal_python-redis: needs-triage
jammy_python-redis: needs-triage
kinetic_python-redis: needs-triage
devel_python-redis: needs-triage
