Candidate: CVE-2021-33430
PublicDate: 2021-12-17 19:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33430
 https://github.com/numpy/numpy/issues/18939
 https://github.com/numpy/numpy/pull/18989
 https://github.com/numpy/numpy/commit/16f7824b4d935b6aee98298ca4123d57174a6f2e (v1.22.0.dev0)
Description:
 ** DISPUTED ** A Buffer Overflow vulnerability exists in NumPy 1.9.x in the
 PyArray_NewFromDescr_int function of ctors.c when specifying arrays of
 large dimensions (over 32) from Python code, which could let a malicious
 user cause a Denial of Service. NOTE: The vendor does not agree this is a
 vulneraility; In (very limited) circumstances a user may be able provoke
 the buffer overflow, the user is most likely already privileged to at least
 provoke denial of service by exhausting memory. Triggering this further
 requires the use of uncommon API (complicated structured dtypes), which is
 very unlikely to be available to an unprivileged user.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to: iconstantin
CVSS:
 nvd: CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H [5.3 MEDIUM]


Patches_numpy:
upstream_numpy: released (1:1.21.4-2)
trusty_numpy: ignored (out of standard support)
xenial_numpy: ignored (out of standard support)
focal_numpy: needs-triage
hirsute_numpy: ignored (reached end-of-life)
impish_numpy: ignored (reached end-of-life)
jammy_numpy: needs-triage
devel_numpy: needs-triage
