Candidate: CVE-2021-3733
PublicDate: 2021-09-02 00:00:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3733
 https://bugs.python.org/issue43075
 https://github.com/python/cpython/pull/24391
 https://github.com/python/cpython/commit/7215d1ae25525c92b026166f9d5cac85fb1defe1 (master)
 https://github.com/python/cpython/commit/a21d4fbd549ec9685068a113660553d7f80d9b09 (3.9.5)
 https://github.com/python/cpython/commit/e7654b6046090914a8323931ed759a94a5f85d60 (3.8.10)
 https://github.com/python/cpython/commit/ada14995870abddc277addf57dd690a2af04c2da (3.7.11)
 https://github.com/python/cpython/commit/3fbe96123aeb66664fa547a8f6022efa2dc8788f (3.6.14)
Description:
 [Denial of service when identifying crafted invalid RFCs]
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to: leosilva
CVSS:


Patches_python3.9:
upstream_python3.9: released (3.9.7-1)
trusty_python3.9: ignored (out of standard support)
trusty/esm_python3.9: DNE
xenial_python3.9: ignored (out of standard support)
bionic_python3.9: DNE
focal_python3.9: needed
hirsute_python3.9: needed
devel_python3.9: needs-triage

Patches_python3.7:
upstream_python3.7: needs-triage
trusty_python3.7: ignored (out of standard support)
trusty/esm_python3.7: DNE
xenial_python3.7: ignored (out of standard support)
bionic_python3.7: needed
focal_python3.7: DNE
hirsute_python3.7: DNE
devel_python3.7: DNE

Patches_python3.5:
upstream_python3.5: needs-triage
trusty_python3.5: ignored (out of standard support)
trusty/esm_python3.5: needed
xenial_python3.5: ignored (out of standard support)
esm-infra/xenial_python3.5: needed
bionic_python3.5: DNE
focal_python3.5: DNE
hirsute_python3.5: DNE
devel_python3.5: DNE
